### PR TITLE
Fix find command bug found in PE-D

### LINKED ISSUE #339: [PE-D][Tester A] UX/UG - Executing a `find` command completely wipes out an active `filter`, preventing intersectional searches
### Steps to Reproduce
1. Launch the application.
2. Execute a filter command to narrow down the client list by location (e.g., `filter l/ActiveSG`). Observe the shortened list.
3. Attempt to search for a specific name *within* that location by executing a find command (e.g., `find John`).
4. Observe the displayed client list.

### Expected Behavior
Ideally, `find` should search within the currently filtered list to allow for intersectional searches (e.g., finding all clients named "John" who work out at "ActiveSG"). If the design decision was strictly to have `find` reset the list and search the entire database instead, this behavior needs to be explicitly documented in the User Guide (similar to how `list` and `sort` behaviors are documented).

### Actual Behavior
The `find` command silently destroys the active `filter` state and searches the entire database. This is jarring UX, as it forces the user to choose between searching by name OR searching by location, severely limiting the app's data retrieval capabilities. Because this reset behavior is completely undocumented, the user is left confused as to why their location filter disappeared.

### Screenshots
*(No specific screenshot attached, behavior observed in UI)*

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by prickloll**
Bug Fixed:

- Fixes #339

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -32,7 +34,8 @@ public FindCommand(NameContainsKeywordsPredicate predicate) {
     @Override
     public CommandResult execute(Model model) {
         requireNonNull(model);
-        model.updateFilteredPersonList(predicate);
+        Set<Person> currentlyDisplayed = Set.copyOf(model.getFilteredPersonList());
```
Comment (jianrontan) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:37]: Before this PR, `find John` after `list` (or with no filter active) searched all clients. Now it only searches `currentlyDisplayed`, which after `list` is all clients, so that case still works. But after `find Alex`, running `find John` searches only within the Alex results, not all clients. This means consecutive `find` calls narrow the results progressively, which users won't expect and is not documented.

Is this the intended behaviour? If not, `find` should reset to the full list when no `filter` is active, and only intersect when a filter command is active. These are two different predicates and need to be distinguished.

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 2]
```diff
@@ -32,7 +34,8 @@ public FindCommand(NameContainsKeywordsPredicate predicate) {
...
+        model.updateFilteredPersonList(predicate.and(person -> currentlyDisplayed.contains(person)));
```
Comment (jianrontan) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:38]: I think that this lambda can be simplified:
`predicate.and(person -> currentlyDisplayed.contains(person))`

Could use a method reference: `predicate.and(currentlyDisplayed::contains)`

File: docs/UserGuide.md [hunk 3]
```diff
@@ -277,6 +277,7 @@ Format: `find KEYWORD [MORE_KEYWORDS]`
 * Only full words will be matched e.g. `Han` will not match `Hans`
 * Clients matching at least one keyword will be returned (i.e. `OR` search).
```
Comment (jianrontan) [inline docs/UserGuide.md]: This is now only true within the current display, worth adding "of the currently displayed list" for clarity.

**Review by jianrontan — COMMENTED** [review]
LGTM! Some clarifications needed before merging.

File: src/main/java/seedu/address/logic/commands/FindCommand.java (hunk 1 above)
Comment (prickloll) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:37]: The narrowed search is indeed the intended behavior due to the limited number of lines I can edit. The best alternative would be to indicate to the users to run `list` to reset to find within the entire client list again.

File: src/main/java/seedu/address/logic/commands/FindCommand.java (hunk 2 above)
Comment (prickloll) [reply src/main/java/seedu/address/logic/commands/FindCommand.java:38]: Yes it can but in terms of readability, I opted for the approach above.
