### PR TITLE
Make clear output accurate

### LINKED ISSUE #361: [PE-D][Tester C] clear feedback message is misleading about what was cleared
Environment
OS: macOS 26.3
Java: 17
App version: v1.5

Steps to reproduce
Launch the application using java -jar.
Create at least one workout log (e.g., add a client, then run log 1).
Run clear.

Expected
Feedback should clearly state that both clients and workout logs were cleared (UG says clear clears all clients and workout logs).

Actual
Feedback says Address book has been cleared! (does not mention workout logs, and uses legacy “Address book” wording).

Image
Image
Image
Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by b2-4ac**
This pull request does the following:
- Changes the output of the clear command to make it more accurate to its use case.

Closes #361

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ClearCommand.java [hunk 1]
```diff
@@ -11,8 +11,9 @@
 public class ClearCommand extends Command {
 
     public static final String COMMAND_WORD = "clear";
-    public static final String MESSAGE_SUCCESS = "Address book has been cleared!";
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Clears all entries from the address book.\n"
+    public static final String MESSAGE_SUCCESS = "Address book and Workout Log Book have been cleared!";
```
Comment (ryangoh206) [inline src/main/java/seedu/address/logic/commands/ClearCommand.java]: Should it state "Client entries and workout log entries have been cleared" instead?

**Review by ryangoh206 — COMMENTED** [review]
Clarification requested regarding the changes. It may constitute a bug as we still refer to address book.

**Comment by ryangoh206** [comment]
LGTM!
