### PR TITLE
Fix bugs related to FilterCommand identified in Alpha Test 

### LINKED ISSUE #149: [Bug] rate command: rate clears the filtered list after find
**Steps to reproduce:**

1. Run `find <name>`.
2. Run `rate 1 r/99`.

**Expected Behavior:** 
Filtered results should remain visible (or behavior documented clearly).

**Actual Behaviour:** 
List resets to all persons.

### LINKED ISSUE #153: [Bug] status command: status clears filtered list after find
**Steps to reproduce:**

1. Run `find <name>`.
2. Run `status 1 s/inactive`.

**Expected Behavior:** 
Filtered list should remain.

**Actual Behaviour:** 
List resets to all persons.

### LINKED ISSUE #156: [Bug] note command: note clears filtered list after find
**Steps to reproduce:**

1. Run `find <name>`.
2. Run `note 1 n/updated`.

**Expected Behavior:** 
Filtered list should remain.

**Actual Behaviour:** 
List resets to all persons.

### LINKED ISSUE #177: [Bug] Measure command: Clears filtered list after find
`MeasureCommand.java:94` calls `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)`, resetting any active `find` filter after every `measure` command.

Steps to reproduce:
1. `find Alex`
2. `measure 1 h/175.5`
3. Observe: the filtered list is replaced with all clients

### LINKED ISSUE #189: [Bug] Plan command: Error message shows "FULL_BODY" but correct input format is "FULL BODY"
The error message in `Plan.java` reads:

`"Plan should be exactly one category: PUSH, PULL, LEGS, CORE, CARDIO, MOBILITY, FULL_BODY, or CONDITIONING."`

However, `FULL_BODY` (with underscore) is not a valid input — the correct input is `FULL BODY` (with space), as documented in the UG. A user who copies `FULL_BODY` from the error message will receive another error.

Steps to reproduce:
1. `plan 1 wp/INVALID`
2. Observe error message listing `FULL_BODY`
3. `plan 1 wp/FULL_BODY`
4. Observe: command succeeds — actually this input works due to internal normalisation, but the error message is still inconsistent with the UG which says `FULL BODY`

### LINKED ISSUE #208: [Bug] Filter command: Success message says "persons listed!" instead of "clients listed!"
The success message uses `Messages.MESSAGE_PERSONS_LISTED_OVERVIEW` which reads:

`%1$d persons listed!`

The product consistently uses "clients" in user-facing text throughout the UG and UI. "Persons" is AB3 terminology that was not updated.

Steps to reproduce:
1. `filter l/ActiveSG`
2. Observe: message shows "X persons listed!"

### LINKED ISSUE #209: [Bug] Filter command: Clears filter after any edit/measure/rate/plan/status command
Any modification command (`edit`, `measure`, `rate`, `plan`, `status`, `note`) calls `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)` after execution, resetting any active `filter` applied beforehand.

A trainer who filters by gym location to work on a subset of clients loses the filter after every single modification.

Steps to reproduce:
1. `filter l/ActiveSG`
2. Observe: filtered list shown
3. `edit 1 p/99999999`
4. Observe: all clients shown — filter is gone

### LINKED ISSUE #210: [Bug] Filter command: Clients with no preset location can be found by filtering for "No Location Specified"
Clients added without a location are stored with `Location: No Location Specified`. A user running `filter l/No Location Specified` will retrieve these clients, exposing an internal default value as a searchable location keyword.

The UG does not document this behaviour, and "No Location Specified" is not a real gym location — it is an internal placeholder that should not be user-visible as a filter target.

Steps to reproduce:
1. Add a client without specifying a location
2. `filter l/No Location Specified`
3. Observe: the client appears in filtered results

### PR DESCRIPTION
**Pull request by prickloll**
Fixes #208, Fixes #209 and Fixes #210

This also indirectly Fixes #149, Fixes #153, Fixes #156, Fixes #177 and Fixes #189 in relation to the find command.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FilterCommandParser.java [hunk 1]
```diff
@@ -25,15 +25,17 @@ public FilterCommand parse(String args) throws ParseException {
...
-                .filter(value -> !value.isEmpty())
                 .map(value -> value.replaceAll("\\s+", " ").trim())
                 .collect(Collectors.toList());
 
         if (locationKeywords.isEmpty()) {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, FilterCommand.MESSAGE_USAGE));
         }
 
+        if (locationKeywords.size() > 1 && locationKeywords.stream().anyMatch(String::isEmpty)) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, FilterCommand.MESSAGE_USAGE));
```
Comment (ryangoh206) [inline src/main/java/seedu/address/logic/parser/FilterCommandParser.java]: Since this is the specific case for when there are more than 1 location keywords and one of them is empty, is it better to place a specific message to point the user in that direction.
E.g. `For multiple l/ prefixes, none of them can be blank`
