### PR TITLE
Fix help message behavior found in PE-D

### LINKED ISSUE #368: [PE-D][Tester A] UI/UX - Redundant and disruptive Help Window pop-up contradicts CLI-first design
### Steps to Reproduce
1. Launch the application.
2. Type `help` into the command box and press Enter.
3. Observe both the Result Display and the external window that appears.

### Expected Behavior
PowerRoster is explicitly "optimised for text commands" for trainers who "prefer keyboard-driven workflows". As documented in the DG, the `help` feature has been enhanced to produce a "combined usage string" directly in the CLI. Therefore, the `help` command should only display this text in the Result Display. The external pop-up window (default AB3 behavior) should be fixed to a dedicated hotkey (e.g., F1) or removed entirely to prevent breaking the user's flow.

### Actual Behavior
Executing `help` currently triggers two simultaneous actions: it displays the usage instructions in the CLI *and* forces an external GUI window to pop up. This is redundant and disruptive for the target user (a fast-typist), as it forces them to take their hands off the keyboard to close an unwanted window just to continue using the CLI.

### Screenshots
Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by prickloll**
Bugs Fixed

- Fixes #368

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/HelpCommandTest.java [hunk 1]
```diff
@@ -13,14 +13,16 @@
 import seedu.address.model.ModelManager;
 
 public class HelpCommandTest {
+    private static final String USER_GUIDE_REFERENCE =
```
Comment (jianrontan) [inline src/test/java/seedu/address/logic/commands/HelpCommandTest.java]: This seems like a duplicate. `private static final String USER_GUIDE_REFERENCE = "Refer to the user guide: ...";` is already in `HelpCommand.java` no?

**Review by jianrontan — COMMENTED** [review]
Other than this, LGTM!

File: src/test/java/seedu/address/logic/commands/HelpCommandTest.java (hunk 1 above)
Comment (prickloll) [reply src/test/java/seedu/address/logic/commands/HelpCommandTest.java]: The same string is set as private in HelpCommand.java which was why I created a duplicate. However, this was unnecessary. I will fix to be public instead so I can avoid this duplicate. Thanks!
