### PR TITLE
Fix bugs identified in PE-D

### LINKED ISSUE #331: [PE-D][Tester C] DG manual testing expected result for delete is inaccurate
Environment
OS: macOS 26.3
Java: 17
App version: v1.5

Steps to reproduce
Launch the app with at least one client shown.
Run delete 1.
Read the result message.

Expected
As stated in DG manual testing, details of the deleted client should be shown.

Actual
Only the deleted client’s name is shown (Deleted Client: <name>), not full details.

Image
Image
Image
Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #350: [PE-D][Tester D] Missing status in view panel
When using the view panel, the status of the client is not shown in the panel. This omission is not noted in the user guide, mentioning that `view` shows the "full profile".

Expected: All details of the client is shown in the view panel
Actual: Status is not shown in the view panel

Commands to recreate:
```
add n/Jane Tan g/F dob/01/01/1990 p/91234567 e/s@test.com a/123 Street
status 1 s/inactive
view 1
```

Screenshot:

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #365: [PE-D][Tester B] Glossary is incomplete; key terms such as CLI, GUI, and MSS are not defined
The Developer Guide includes a glossary section, but I think it is incomplete as several important terms used throughout the document are not defined.

In particular, terms such as Command Line Interface (CLI) and Graphical User Interface (GUI) are central to the product’s design and target user profile, and are repeatedly referenced across the documentation. However, they are not included in the glossary. Even though you have already explain these two terms, I think you need to add them to glossary as it is more like a "summary". Just like you add mainstream OS into the glossary.

Image

Additionally, the term MSS (Main Success Scenario) is used in the use case descriptions, but is also not defined in the glossary. As shown in the screenshot, MSS appears as a heading without prior explanation, which may be unclear to readers unfamiliar with use case terminology (e.g. they may not be our course student).

Image

I think this is problematic because the glossary serves as a consolidated reference for key terms used in the document. Even if some of these terms are explained earlier in context, they should still be included in the glossary for quick reference and consistency.

Suggested Improvement:
I think it would be helpful to expand the glossary to include definitions for key terms such as:

CLI (Command Line Interface)
GUI (Graphical User Interface)
MSS (Main Success Scenario)

This would improve clarity and make the glossary a more complete and useful reference for readers.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #373: [PE-D][Tester D] Inaccurate PUML diagram showing wrong arguments
The diagram `DeleteSequenceDiagram.puml` (attached below) shows that `DeleteCommand` calls `deletePerson(1)`. However, the underlying code at `DeleteCommand.java:45` shows it accepting a Person object instead of an index.

Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #374: [PE-D][Tester E] Bug report: Success message uses incorrect grammar "1 clients listed!" instead of "1 client listed!"
## Success message uses incorrect grammar "1 clients listed!" instead of "1 client listed!"

When a command results in exactly 1 client being listed (e.g., `find`), the feedback message reads "1 clients listed!" which is grammatically incorrect. It should read "1 client listed!" (singular).

**Steps to reproduce:**
1. Ensure there is exactly one client named `Hans` in PowerRoster
2. Run `find Hans`

**Expected:** `1 client listed!`

**Actual:** `1 clients listed!`

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #377: [PE-D][Tester D] Missing part of PUML diagram
The diagram `DeleteSequenceDiagram.puml` (attached below) omits the call to `model.clearLogs(personToDelete)` at `DeleteCommand.java:46`, not showing that deleting a person will also delete the associated workout logs.

Image

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #380: [PE-D][Tester E] Bug report: `edit` command accepts email addresses without a top-level domain, violating documented email format rules
## `edit` command accepts email addresses without a top-level domain, violating documented email format rules

The UG specifies that the email domain must be "made of labels separated by dots" and "the final label (e.g. com) must be at least 2 characters". However, the `edit` command accepts emails with no dot in the domain (e.g., `not@nemail`), which has no final label.

**Steps to reproduce:**
1. Ensure at least one client exists (e.g., run `list`)
2. Run `edit 1 e/not@nemail`

**Expected:** Error message about invalid email format — domain must have labels separated by dots with the final label being at least 2 characters

**Actual:** Client email is successfully updated to the invalid value `not@nemail`

**Screenshots:**

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by ryangoh206**
Bugs fixed:
- Fixes #350
- Fixes #374
- Fixes #331
- Fixes #365
- Fixes #373
- Fixes #377
- Fixes #380

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Email.java [hunk 1]
```diff
@@ -14,16 +14,16 @@ public class Email {
...
     private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
     private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE
-            + "([" + SPECIAL_CHARACTERS + "]" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    private static final String DOMAIN_PART_REGEX = ALPHANUMERIC_NO_UNDERSCORE
-            + "(-" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    private static final String DOMAIN_LAST_PART_REGEX = "(" + DOMAIN_PART_REGEX + "){2,}$"; // At least two chars
-    private static final String DOMAIN_REGEX = "(" + DOMAIN_PART_REGEX + "\\.)*" + DOMAIN_LAST_PART_REGEX;
+        + "([" + SPECIAL_CHARACTERS + "]" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
+    private static final String DOMAIN_LABEL_REGEX = ALPHANUMERIC_NO_UNDERSCORE
+        + "(-" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
```
Comment (prickloll) [inline src/main/java/seedu/address/model/person/Email.java:25]: Just a clarification on the email, is the intention to allow the email `user@domain.c`? Currently, in the UG it is stated that at least 2 characters are required for TLD while here the restriction is at least 1 character.

File: src/main/java/seedu/address/model/person/Email.java [hunk 2]
```diff
@@ -14,16 +14,16 @@ public class Email {
...
+    private static final String DOMAIN_REGEX = "(" + DOMAIN_LABEL_REGEX + "\\.)+" + DOMAIN_LABEL_REGEX + "$";
     public static final String VALIDATION_REGEX = LOCAL_PART_REGEX + "@" + DOMAIN_REGEX;
```
Comment (prickloll) [inline src/main/java/seedu/address/model/person/Email.java:27]: The ug should also reflect the same changes if the regex is what is desired. 
* `EMAIL_ADDRESS` must follow the rules below (format: `local-part@domain`, e.g. `alex@example.com`):
  * Local-part (before `@`)
    * Uses letters, digits, and `+`, `.`, `-`
    * Must start and end with a letter or digit
    * Special characters cannot appear consecutively
  * Domain (after `@`)
    * Made of labels separated by dots (`.`). At least 1 dot is required
    * Each label must start and end with a letter or digit
    * Hyphens are allowed inside a label, but not consecutively
    * Top-Level Domain (TLD):  The final label (e.g. `com`) must be at least 1 character

**Review by prickloll — COMMENTED** [review]
LGTM! Just some minor regex clarification for the email component.

File: src/main/java/seedu/address/model/person/Email.java (hunk 1 above)
Comment (ryangoh206) [reply src/main/java/seedu/address/model/person/Email.java:25]: The check for the final label to be at least 2 characters is done below at line 53. Cheers

File: src/main/java/seedu/address/model/person/Email.java (hunk 2 above)
Comment (ryangoh206) [reply src/main/java/seedu/address/model/person/Email.java:27]: Sorry I do not quite get what you mean. I believe the regex matches the UG if it is what you pasted.

File: src/main/java/seedu/address/model/person/Email.java (hunk 1 above)
Comment (prickloll) [reply src/main/java/seedu/address/model/person/Email.java:25]: ok my bad I missed it. Cheers.

File: src/main/java/seedu/address/model/person/Email.java (hunk 2 above)
Comment (prickloll) [reply src/main/java/seedu/address/model/person/Email.java:27]: Thanks for the clarification. The UG does not need to be updated. Thanks.

**Comment by prickloll** [comment]
LGTM!
