### PR TITLE
Fix conditions under which Sample Workout Log data is used

### LINKED ISSUE #335: [PE-D][Tester C] Missing workoutlogbook.json injects sample workout logs into existing user data
Environment
OS: macOS 26.3
Java: 17
App version: v1.5

Steps to reproduce
Prepare a data folder that contains a valid addressbook.json with your own client(s), but no workoutlogbook.json.
Launch the application using java -jar.
Run any command that triggers save (e.g. list).
Open the newly created data/workoutlogbook.json.

Expected
Because the workout log file was missing, the app should initialize an empty workout log book for the existing clients.

Actual
The app initializes and saves the built-in sample workout logs instead (with sample client IDs unrelated to the user’s client data).

-------------
Labels: `severity.High` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by b2-4ac**
This pull request does the following:
- Changes the conditions under which Sample Data is used for workout logs
  - If addressbook is present but no workout logs are present, starts with empty workoutlog book
  - If addressbook is absent and no workout logs are present, starts with sample data
- Treats a corrupted addressbook as if it is present

Closes #335

### CODE REVIEW

File: src/main/java/seedu/address/MainApp.java [hunk 1]
```diff
@@ -101,10 +103,16 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
...
-            if (!workoutLogBookOptional.isPresent()) {
+            if (!workoutLogBookOptional.isPresent() && !isAddressBookPresent) {
                 logger.info("Creating new workout log file " + storage.getWorkoutLogBookFilePath());
+                initialLogs = SampleDataUtil.getSampleWorkoutLogBook();
+            } else if (!workoutLogBookOptional.isPresent() && isAddressBookPresent) {
+                logger.info("AddressBook detected but no WorkoutLogBook detected."
+                        + " Starting with empty WorkoutLogBook");
+                initialLogs = new WorkoutLogBook();
+            } else {
+                initialLogs = workoutLogBookOptional.get();
```
Comment (ryangoh206) [inline src/main/java/seedu/address/MainApp.java:114]: May I clarify that if there is no address book but there is a workout book. A new address book will be created with the sample data but the workout book will be used. If so, will the users run into an issue where workouts get assigned to the wrong user.

**Review by ryangoh206 — COMMENTED** [review]
Just need to clarify something before merging.

File: src/main/java/seedu/address/MainApp.java (hunk 1 above)
Comment (b2-4ac) [reply src/main/java/seedu/address/MainApp.java:114]: That is the current implementation yes. I am not sure this is a problem as it is unlikely a user would have a the workoutlog book present if they dont also have the addressbook present. Given our current implementation, even if the user wanted to add clients and link them to an existing workoutlog book, it would not be possible given that they are linked by a clientid, and generating a new user with the same name would not yield the same ID

Comment (ryangoh206) [reply src/main/java/seedu/address/MainApp.java:114]: That is true, that may be a result of extreme behaviour and not counted as a bug. Also, the ID also prevents the association between old workoutlogs and new users, etc.
